version: 2.1
orbs:
    aws-ecr: circleci/aws-ecr@8.1.3

jobs:
    build:
        docker:
            - image: cimg/node:18.8.0
        steps:
            - checkout
            - aws-ecr/build-and-push-image

workflows:
    build:
        jobs:
            - build
