version: 2.1
orbs:
    aws-ecr: circleci/aws-ecr@8.1.3

jobs:
    build:
        docker:
            - image: cimg/node:18.8.0
        steps:
            - checkout
            - aws-ecr/build-and-push-image:
                  create-repo: false
                  repo: matchup
                  repo-scan-on-push: true
                  tag: 'latest'
                  role-arn: 'arn:aws:iam::$ACCOUNT_ID:role/ecr-manager'
                  registry-id: $ACCOUNT_ID
                  region: 'eu-central-1'

workflows:
    build:
        jobs:
            - build
