version: 2.1
orbs:
    aws-ecr: circleci/aws-ecr@8.1.3
    ggshield: gitguardian/ggshield@1.1.4
    snyk: snyk/snyk@1.2.3

jobs:
    snyk-scan:
        docker:
            - image: cimg/node:18.11.0
        steps:
            - checkout
            - run:
                  command: npm ci
            - snyk/scan:
                  severity-threshold: high
    build:
        docker:
            - image: cimg/base:2022.10
        steps:
            - checkout
            - setup_remote_docker:
                  version: 20.10.14
            - aws-ecr/build-and-push-image:
                  create-repo: false
                  repo: matchup
                  repo-scan-on-push: true
                  tag: 'latest'
                  role-arn: 'arn:aws:iam::$ACCOUNT_ID:role/ecr-manager'
                  region: 'eu-central-1'
                  extra-build-args: '--build-arg aws_appsync_graphqlEndpoint=$aws_appsync_graphqlEndpoint --build-arg aws_appsync_apiKey=$aws_appsync_apiKey --build-arg aws_user_files_s3_bucket=$aws_user_files_s3_bucket'

workflows:
    build:
        jobs:
            - ggshield/scan:
                  name: ggshield-scan
                  base_revision: << pipeline.git.base_revision >>
                  revision: <<pipeline.git.revision>>
            - snyk-scan
            - build:
                  requires:
                      - ggshield-scan
                      - snyk-scan
