version: 2.1
orbs:
    aws-ecr: circleci/aws-ecr@8.1.3
    ggshield: gitguardian/ggshield@1.1.4

jobs:
    build:
        docker:
            - image: cimg/base:2022.10
        steps:
            - checkout
            - setup_remote_docker:
                  version: 20.10.14
            - aws-ecr/build-and-push-image:
                  create-repo: false
                  repo: matchup
                  repo-scan-on-push: true
                  tag: 'latest'
                  role-arn: 'arn:aws:iam::$ACCOUNT_ID:role/ecr-manager'
                  region: 'eu-central-1'

workflows:
    scan:
        jobs:
            - ggshield/scan:
                  name: ggshield-scan
                  base_revision: << pipeline.git.base_revision >>
                  revision: <<pipeline.git.revision>>
    build:
        jobs:
            - build
