import type { NextPage } from 'next';
import SkillsCard from '../components/cards/Skills.Card';
import SlotsCard from '../components/cards/Slots.Card';

import { initMap } from '../utils/MapSearch.util'

const Home: NextPage = () => {
<<<<<<< HEAD
  console.log(initMap())
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.GOOGLE_MAPS_API_KEY}&libraries=places&callback=initMap`}>
        </script>
      </Head>

      <main className={styles.main}>
      <nav>
        <Link href="/">
          <span>Home</span>
        </Link>
        <Link href="/Profile/SignIn">
          <span>Sign In</span>
        </Link>
        <Link href="/Organize">
          <span>Host a MatchUp</span>
        </Link>
      </nav>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
=======
<<<<<<< HEAD
  return <h1>something</h1>;
=======
  return (
    <>
      <SkillsCard skillLevel="advanced"></SkillsCard>
      <SlotsCard attending={2} slots={10}></SlotsCard>
    </>
  );
>>>>>>> main
};

export default Home;
>>>>>>> 190608a1041f540b509581916ee8ad8cbb558e35
