/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: process.env.aws_project_region,
  aws_appsync_graphqlEndpoint: process.env.aws_appsync_graphqlEndpoint,
  aws_appsync_region: process.env.aws_appsync_region,
  aws_appsync_authenticationType: process.env.aws_appsync_authenticationType,
  aws_appsync_apiKey: process.env.aws_appsync_apiKey,
  aws_cognito_identity_pool_id: process.env.aws_cognito_identity_pool_id,
  aws_cognito_region: process.env.aws_cognito_region,
  aws_user_pools_id: process.env.aws_user_pools_id,
  aws_user_pools_web_client_id: process.env.aws_user_pools_web_client_id,
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL', 'GIVEN_NAME', 'FAMILY_NAME'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      'REQUIRES_LOWERCASE',
      'REQUIRES_NUMBERS',
      'REQUIRES_SYMBOLS',
      'REQUIRES_UPPERCASE',
    ],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_user_files_s3_bucket: process.env.aws_user_files_s3_bucket,
  aws_user_files_s3_bucket_region: process.env.aws_user_files_s3_bucket_region,
  geo: {
    amazon_location_service: {
      region: 'us-east-1',
      search_indices: {
        items: ['placeindex92e6cd50-dev'],
        default: 'placeindex92e6cd50-dev',
      },
      maps: {
        items: {
          'mapf19b652b-dev': {
            style: 'VectorEsriLightGrayCanvas',
          },
        },
        default: 'mapf19b652b-dev',
      },
    },
  },
};

export default awsmobile;
